CREATE DATABASE passbolt;
GRANT ALL PRIVILEGES ON passbolt.* TO 'passbolt'@'%' IDENTIFIED BY 'P4ssb0lt';
FLUSH PRIVILEGES;

CREATE DATABASE passbolt2;
GRANT ALL PRIVILEGES ON passbolt2.* TO 'passbolt2'@'%' IDENTIFIED BY 'P4ssb0lt2';
FLUSH PRIVILEGES;