CREATE DATABASE passbolt;
GRANT ALL PRIVILEGES ON passbolt.* TO 'passbolt'@'%' IDENTIFIED BY 'P4ssb0lt';
FLUSH PRIVILEGES;

CREATE DATABASE passbolt2;
GRANT ALL PRIVILEGES ON passbolt2.* TO 'passbolt'@'%' IDENTIFIED BY 'P4ssb0lt';
FLUSH PRIVILEGES;